# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4ac274f0529979afe56e2ebc7a04200d"
name = "social-auto-post"
application_url = "https://collective-rural-edges-downloaded.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "l4-dev-shop.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://collective-rural-edges-downloaded.trycloudflare.com/auth/callback",
  "https://collective-rural-edges-downloaded.trycloudflare.com/auth/shopify/callback",
  "https://collective-rural-edges-downloaded.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
